# Generated by Django 4.2.1 on 2023-05-17 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('diagnosis', models.CharField(max_length=100)),
                ('medications', models.TextField()),
                ('allergies', models.TextField()),
                ('symptoms', models.TextField()),
                ('doctor_notes', models.TextField()),
                ('follow_up_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='users.patient')),
            ],
        ),
    ]
